name: Check URLs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install awesome_bot
      run: gem install awesome_bot

    - name: Check URLs
      run: awesome_bot --allow-redirect --allow-dupe --allow-timeout --set-timeout 5 --white-list localhost,**/*.lyx *.lyx